### ISSUE TITLE
Update draw call warnings for soft and hard thresholds

### ISSUE THREAD

**Issue by Strowy** [ActuatorDigital/Clarity#12]
## Describe the task

Update the draw call warning functionality to have:
- a lower 'soft' threshold where a warning will log if you go over
- a 'hard' threshold where an error will log if you go over

The current behaviour is all-or-nothing, as a warning is only logged if you exceed the threshold, and no notice at all if even marginally under that threshold.

## Completed When

- [x] A lower 'soft' threshold where a warning will log if you go over
- [x] A 'hard' threshold where an error will log if you go over

**Comment by stevehalliwell** [comment]
This is slightly annoying as to get upper and lower limits, we either duplicate all settings or use vec2 or write our own gui for them.
